services:
  db:
    image: postgres:16-alpine
    container_name: local_postgres
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
      TZ: Asia/Jakarta
    ports:
      - "${DB_PORT:-5432}:5432" # ganti DB_PORT jadi 5433 kalau 5432 bentrok
    volumes:
      - dbdata:/var/lib/postgresql/data
      # Opsi seed awal: taruh file .sql di ./docker/init (akan jalan saat volume kosong/baru)
      - ./docker/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  dbdata:
